### ISSUE TITLE
Ability to save historic version of the IATI dataset

### ISSUE THREAD

**Issue by lewis-sternberg** [devinit/ddw-analyst-ui#262] opened 2020-07-28 14:03 UTC
It would be beneficial to be able to save a particular version of the IATI dataset (e.g. that used for a publication) on the DDW to run future queries against.

**Comment by wakibi** [comment] 2020-09-11 15:14
@edwinmp isn't this a duplicate of #185?

**Comment by wakibi** [comment] 2020-10-14 14:09
@edwinmp yes it is. @k8hughes we should close this and move it to #185

**Comment by edwinmp** [comment] 2020-10-19 09:56
Only front-end side left on this, so I'm going to tie it to #187

**Closed as completed** 2020-10-19 09:56 UTC

**Comment by edwinmp** [comment] 2020-11-02 11:14
@lewis-sternberg we've added the ability to save a historic version of a dataset. We still can't perform query operations on these saved instances but they can be downloaded as CSV and processed offline.
https://ddw.devinit.org/datasets/
![image](https://user-images.githubusercontent.com/5672438/97861720-4095a600-1d15-11eb-879f-2d03bfe31e77.png)

I hope this is fine for now as we look into adding the ability to query these saved datasets from within the DDW.

We can also save historic versions of entire datasources, though with the size of IATI, that may take a while & result in a very large download file.
https://ddw.devinit.org/sources/
![image](https://user-images.githubusercontent.com/5672438/97862106-db8e8000-1d15-11eb-90c5-4de61b4b1b34.png)
