### ISSUE TITLE
Progress during save and export

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#313] opened 2020-09-07 16:05 UTC
IATI queries can now take 5 minutes to save or export.  Is it possible to display a progress message?

**Comment by k8hughes** [comment] 2020-09-10 09:22
I think there are two issues at play here.  Bill queried for one activity today and it took 5 mins for the query to resolve - this is more of an optimisation issue.

@wakibi  can you investigate what is going on here?

**Comment by edwinmp** [comment] 2020-09-10 09:28
Duplicate of #260 ... also @k8hughes which action took 5 mins? Saving the dataset, querying the data or exporting to csv? In any case, it'll help to have the a link to the dataset in question for troubleshooting...

**Comment by k8hughes** [comment] 2020-09-10 09:48
@bill-anderson  will need to add the details here...

**Comment by k8hughes** [comment] 2020-09-10 09:49
Or do we close this if it is a duplicate?

**Comment by wakibi** [comment] 2020-09-11 15:19
Just to answer the question as is, this will be a long short! We do not know the amount of data (size of file) before hand, and if we are to try and create a hack around it, it may still not serve the purpose. The data is generated on the fly, which makes it extremely hard! The best we can do is get the time it will take for a query to be run.

**Comment by bill-anderson** [comment] 2020-09-11 16:24
https://www.pgcon.org/2013/schedule/attachments/282_pg-progress.pdf

Any insights here?

**Comment by k8hughes** [comment] 2020-09-14 07:30
I am going to close this issue so we can keep all the thinking in the same place on #260

**Closed as completed by k8hughes** 2020-09-14 07:30 UTC
Labels: enhancement
