### ISSUE TITLE
Unable to access FTS data

### ISSUE THREAD

**Issue by niklasrie** [devinit/ddw-analyst-ui#370] opened 2020-11-11 12:27 UTC
I tried to perform several distinct queries on FTS data (query numbers 789, 790 and 791) but in every case they come up empty. Not sure what the issue is there.
The data search on the FTS website however also seems stuck and does not spit out data for me - might be related, not sure. 

Wondering, if the data pull from FTS is indeed broken (potentially due to issues on their side) - do we have frozen datasets from past data pulls we could use instead?

**Comment by k8hughes** [comment] 2020-11-11 12:51
@wakibi could you look into this asap?

**Comment by wakibi** [comment] 2020-11-12 08:55
Hi @niklasrie, the data is okay and working fine. The problem is that the maximum year is 2014 for both columns you are filtering against, and you are filtering for 2018-2020 data. It could be an issue at the FTS side that they haven't updated data. I have double checked our end. Cheers.

**Comment by niklasrie** [comment] 2020-11-12 10:46
Thanks for checking @wakibi - so the data up until 2014 is therefore okay and working fine?

FTS certainly has data that is more recent than 2014 - see for example https://fts.unocha.org/data-search/results/incoming?usageYears=2020

So I'm not sure why we're not pulling this more recent data?

**Comment by wakibi** [comment] 2020-11-13 08:26
@niklasrie the data has been updated and works okay when queried directly in the DB, still figuring out why it's not being returned on the FE. Quick note, some of the data in those two columns is in this format;
```
                            destination_UsageYear_name                             
-----------------------------------------------------------------------------------
 2019 | 2018 | 2017 | 2020
 2018 | 2019 | 2020 | 2021 | 2022 | 2023
 2017 | 2016 | 2015
 2015 | 2016 | 2017 | 2018 | 2019
 2015 | 2016 | 2018 | 2017
```
I am not sure if the query as is would pick all data you are interested in?

**Comment by k8hughes** [comment] 2020-11-20 12:17
@wakibi any update on this?

**Comment by k8hughes** [comment] 2020-12-01 11:26
@edwinmp can you leave a note on this issue that says what is needed in the future so that we don't forget?

**Comment by edwinmp** [comment] 2020-12-08 10:38
From Slack

@wakibi  ignore my earlier conclusion ... narrowed down the actual problem to aliases ... every time u save a dataset, aliases are generated for its columns. Something seems to have interrupted that for these datasets, probably a deployment ... saving them a second time should fix the problem.
This should be fixed https://ddw.devinit.org/queries/data/790/
Try saving this one again then test https://ddw.devinit.org/queries/data/791/
@niklasrie  the above is a temporary quick fix. I'll make time and do a proper one. Previews are exempt from this bug, so if you need to check if it's a bug or there's really no data, preview your dataset

**Comment by edwinmp** [comment] 2021-02-17 14:28
@ThatcherK
**Background**
DB column names don't always appear in nicely readable formats, so we created the alias feature to give columns better names. The default alias mapping is found in the `[meta_columns.csv](https://github.com/devinit/ddw-analyst-ui/blob/develop/data_updates/manual/CSV/meta_columns.csv)` file, but a user still has the ability to add their own aliases for a particular dataset.

Dataset data on the FE uses aliases for column names, so if this is interrupted, stuff goes a little nuts, like in this issue.

Aliases are created on the backend every time a dataset is saved or updated.
https://github.com/devinit/ddw-analyst-ui/blob/develop/core/serializers.py#L188
https://github.com/devinit/ddw-analyst-ui/blob/develop/core/serializers.py#L226

**Solution**

1. We're going to add a field to the [Operation](https://github.com/devinit/ddw-analyst-ui/blob/develop/core/models.py#L87) model we'll be using to monitor the creation of aliases: `alias_creation_status`
It's an enum with one of three values `done`, `pending`, `error`. Default is `done` cos it's a safe assumption that all existing datasets have aliases generated.

2. In the `OperationSerializer`, make sure to update the above field before and after aliases are created
3. **FE**: On the `[OperationForm](https://github.com/devinit/ddw-analyst-ui/blob/develop/frontend/src/components/OperationForm/OperationForm.tsx#L124)` of the QueryBuilder, watch for the above field and show an alert when `pending` or `error`. Alert message is along the lines of "The creation of column aliases for this dataset was interrupted. Please save this dataset again to generate new aliases"

**Closed as completed** 2021-03-09 08:29 UTC
Labels: enhancement
