### ISSUE TITLE
Multiple edits to queries not saved

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#348] opened 2020-10-05 09:09 UTC
When you edit a previously saved query you have to save after any change to a single step. Changes to more than one step will only save the last change.

**Comment by edwinmp** [comment] 2020-10-05 09:33
Could I have a link to a query as well as steps to reproduce.

**Comment by bill-anderson** [comment] 2020-10-05 09:40
Any query. Edit a step. Edit another step. Save the query. The first edit will not have been saved.

**Comment by edwinmp** [comment] 2020-10-05 09:53
Can't replicate ... all my edits are being retained. The problem may be something else tied to that particular query.

**Comment by k8hughes** [comment] 2020-10-19 09:59
@bill-anderson is this still an issue or should we close it?

**Comment by bill-anderson** [comment] 2020-10-19 10:16
it is an issue, happens all the time.

**Comment by edwinmp** [comment] 2020-10-19 10:17
@devinit/di-devs can someone please try to replicate this.

**Comment by akmiller01** [comment] 2020-10-19 18:41
Hm, I can't replicate it either @edwinmp , maybe it's only taking place with certain types of steps? Also maybe we should change the button text if it's confusing. You cannot just click "Close" after editing the first step, you need to click "Edit step" in-between each change for each step.

**Comment by edwinmp** [comment] 2020-10-19 18:49
So from `Close` to `Cancel`? Then perhaps `Edit Step & Close`

**Comment by akmiller01** [comment] 2020-10-19 18:58
For myself as a user, from `Close` to `Cancel` makes sense (maybe with a "Are you sure you want to undo your changes to your step?"), but I would change `Edit step` to `Confirm changes` or `Apply changes` or something similar.

**Comment by edwinmp** [comment] 2020-10-19 19:02
And have it disabled until the user makes a change ...

**Comment by bill-anderson** [comment] 2020-10-20 07:51
For the record it is not a matter of closing a step. If I edit two steps of a previously saved (and run?) query.Only the last edit is saved when I save the query

**Comment by akmiller01** [comment] 2020-10-20 12:00
Next time it happens, could you record the query ID number here @bill-anderson ? I tried a couple different combinations of step types and wasn't able to get the first not to save.

**Comment by bill-anderson** [comment] 2021-01-12 14:33
If you edit a step and then edit the name (without saving the query in between) the step edit is lost. Happened to me on both 836 and 837 today.

**Comment by k8hughes** [comment] 2021-03-22 12:41
I think we should inestigate this, especially seeing as Bill has defined the problem more clearly for us to be able to work out what is going on.  @edwinmp can you take a look based on Bill's Jan comments and see if you can work out the problem?

**Comment by edwinmp** [comment] 2021-03-22 14:09
Still can't replicate it ... perhaps we've made changes that have since eliminated... @bill-anderson is this still happening? Perhaps it only happens on a particular query type (select, filter... ?)

**Closed as completed** 2021-05-18 08:33 UTC
Labels: bug, can't replicate
