### ISSUE TITLE
Hide IATI check columns from the Query builder

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#261] opened 2020-07-28 11:22 UTC
The ETL transforms the following columns into x_ prefixed columns. They should be hidden from the Query builder.

default_aid_type_code
default_aid_type_vocabulary
default_currency
default_finance_type_code
default_flow_type_code
default_tied_status_code
humanitarian_scope_code
humanitarian_scope_type
humanitarian_scope_vocabulary
recipient_country_code
recipient_country_percentage
recipient_region_code
recipient_region_percentage
recipient_region_vocabulary
sector_code
sector_percentage
sector_vocabulary
transaction_aid_type_code
transaction_aid_type_vocabulary
transaction_date_iso_date
transaction_finance_type_code
transaction_flow_type_code
transaction_recipient_country_code
transaction_recipient_region_code
transaction_recipient_region_vocabulary
transaction_sector_code
transaction_sector_vocabulary
transaction_tied_status_code
transaction_value
transaction_value_currency
transaction_value_date

**Comment by akmiller01** [comment] 2020-07-28 11:47
Hey @bill-anderson , should they be hidden from the column selector but visible in the output? Or removed from the column selector and output entirely?

**Comment by bill-anderson** [comment] 2020-07-28 12:03
Removed from both I think

**Comment by akmiller01** [comment] 2020-07-28 12:09
In that case, can you think of any reason to insert them into postgres at all? Or should we just remove these from the table fullstop?

**Comment by bill-anderson** [comment] 2020-07-28 12:13
I think we can remove them. The one use case would be to check why data might look strange. But I find it's actually easier to patch the iati-identifier into d-portal

**Comment by akmiller01** [comment] 2020-07-31 15:36
Done https://github.com/devinit/ddw-analyst-ui/pull/278

**Comment by bill-anderson** [comment] 2020-08-03 09:17
I can still see them?

**Comment by k8hughes** [comment] 2020-08-05 08:48
@akmiller01 has this issue been completed?  Do we still need it in code review?

**Comment by akmiller01** [comment] 2020-08-05 11:36
I was just deploying it over night, @k8hughes . Need to check of the changes worked.

**Comment by k8hughes** [comment] 2020-08-06 08:53
@bill-anderson could you check this and close the issue if it is working as intended?

**Closed as completed** 2020-08-17 12:03 UTC
Labels: enhancement
