### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#36] opened 2019-02-15 08:11 UTC
Select datasource, select columns, specify joins (left, right, e.t.c)

**Comment by Duncan-Knox** [comment] 2019-04-26 09:56
Hi @edwinmp and @akmiller01. Join has been fantastic to trial and very smooth. One possible bug -   I'm not sure the full range of selection options for queries are available after the joins have been made. For example, if I join dataset 'non-grant government revenue' to  'states of fragility 2018' I won't get the option to perform queries (aggregate, filter, etc) based on the 'states of fragility 2018' columns. Is this one to look into?

**Comment by Duncan-Knox** [comment] 2019-05-01 10:40
At times the options for 'Data Set To Join With' will only show data sets to join that are on page 1 (1-10 of 36) of datasets. Not quite sure what drives this but appears to be the case once queries become more complex.

**Comment by akmiller01** [comment] 2019-05-01 12:56
Probably the same bug that was preventing pagination on the data sources in
the first place.

**Comment by Duncan-Knox** [comment] 2019-05-01 14:56
Possible bug/regression has cropped up on the Join Query. It states  'At least one column mapping is required' above the two columns selected to for joining. This appears to occur when two matching columns have been selected.

**Comment by edwinmp** [comment] 2019-05-02 10:58
Hi @Duncan-Knox ... the above issues on join should be fixed on staging.

**Comment by Duncan-Knox** [comment] 2019-05-02 12:45
Hi @edwinmp, sorry, I still think the most recently posted join bug on 'At least one column mapping is required' is occurring when two matching columns are selected. Is it a case of waiting a little longer for the fix to show?

**Comment by edwinmp** [comment] 2019-05-02 12:49
@Duncan-Knox Could you please clear you cache or try incognito....

**Comment by Duncan-Knox** [comment] 2019-05-03 09:38
Sure, @edwinmp was working on incognito but turned out that a new session was needed. The column mapping bug fix has gone through ok.

**Comment by akmiller01** [comment] 2019-05-03 14:59
Hmm... It really shouldn't default to removing NA. That's really R-exclusive behavior, so it may be missing due to the import routine in R rather than the join. What dataset was missing Namibia @Duncan-Knox ?

**Comment by Duncan-Knox** [comment] 2019-05-03 15:02
Ah the ISO2 has disappeared. The rest of the row is available for Namibia with blank ISO2. Hence the disappearance after merging. That was in 'DI Deflators Constant 2017 USD' but possibly others too @akmiller01

**Comment by Duncan-Knox** [comment] 2019-05-03 15:12
I think this occurs in any dataset with ISO2 for NA that has been manually put together.

**Comment by akmiller01** [comment] 2019-05-03 15:17
I'll be darned. Pandas has the same behavior as R. I'll need to make a fix for this: https://stackoverflow.com/questions/33952142/prevent-pandas-from-interpreting-na-as-nan-in-a-string

**Comment by akmiller01** [comment] 2019-05-03 15:45
Simple fix for NA https://github.com/devinit/ddw-analyst-ui/pull/94

**Comment by Duncan-Knox** [comment] 2019-05-07 10:38
Hi @edwinmp, the following query is not returning any output after hitting save and preview:
http://138.68.138.212/queries/data/93/
Not quite clear why, is it possible that this is a bug?

**Comment by edwinmp** [comment] 2019-05-07 11:31
It's encountering a `500 (Internal Server Error)` ... @akmiller01, could you please troubleshoot with the local data.

**Comment by akmiller01** [comment] 2019-05-07 12:30
```
>>> op = Operation.objects.get(pk=93)
>>> op.build_query()
('SELECT COUNT("sq1".*) FROM (SELECT "sq0".*,"fragility".* FROM (SELECT "di_deflators_2017".*,"oecd_regions".* FROM "repo"."di_deflators_2017" JOIN "repo"."oecd_regions" ON "di_deflators_2017"."country_name"="oecd_regions"."country_name") "sq0" JOIN "repo"."fragility" ON "sq0"."country_name"="fragility"."country_name") "sq1"', 'SELECT "sq0".*,"fragility".* FROM (SELECT "di_deflators_2017".*,"oecd_regions".* FROM "repo"."di_deflators_2017" JOIN "repo"."oecd_regions" ON "di_deflators_2017"."country_name"="oecd_regions"."country_name") "sq0" JOIN "repo"."fragility" ON "sq0"."country_name"="fragility"."country_name"')
>>> op.query_table(1,1,True)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: column reference "country_name" is ambiguous
LINE 1: ...."country_name") "sq0" JOIN "repo"."fragility" ON "sq0"."cou...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/src/core/models.py", line 113, in query_table
    return fetch_data(self.build_query(limit, offset, estimate_count))
  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/src/data/db_manager.py", line 12, in fetch_data
    cursor.execute(main_query)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column reference "country_name" is ambiguous
LINE 1: ...."country_name") "sq0" JOIN "repo"."fragility" ON "sq0"."cou...
```

Two columns named `country_name` so SQL doesn't know which one to choose.

**Comment by edwinmp** [comment] 2019-05-10 13:13
**Note To Self**
Implement join types - BE implementation [here](https://github.com/devinit/ddw-analyst-ui/pull/96/commits/137356f28b622aa9414bb9bd3202aff2607ef15c#diff-7986045d408c2c6f3c426ec5f2bd3bd9R196)

**Comment by k8hughes** [comment] 2019-05-13 08:34
@edwinmp is this "review required" or is there further work to be done?

**Comment by edwinmp** [comment] 2019-05-13 08:58
@k8hughes there's further work to be done resulting from the reviews and testing ...

**Comment by edwinmp** [comment] 2019-05-18 20:02
@Duncan-Knox deployed changes on this, with smarter handling of step column selection ... available columns for a particular step depend on the returned columns of the previous step.

**Comment by Duncan-Knox** [comment] 2019-05-20 10:54
Hi @edwinmp, thank you for the deployment. I have a handful of questions on the join additions if are able to please help out. It is excellent to have these features.  I was wondering what the differences are between: 

left join and left outer join
right join and right outer join
full join and outer join

I ask because some of the SQL sites seem to the say they are the same, but was wondering if there are differences here (the testing I've done so far has the results as being the same in each pairing). 

Also on join, I've tried testing cross join but am not getting output, was wondering if it was to do with the way I was using it. Here are some of the errors being returned, not sure if these are considered bugs?
http://138.68.138.212/queries/data/247/
http://138.68.138.212/queries/data/248/
http://138.68.138.212/queries/build/249/

**Comment by akmiller01** [comment] 2019-05-20 12:47
There's no difference between the outer joins and the regular version: https://www.quora.com/What-is-the-difference-between-left-join-and-left-outer-join-in-sql

Maybe we should remove them... Also Cross join must be done on subqueries, so maybe we exclude that one as well https://www.w3resource.com/sql/joins/cross-join.php

**Comment by Duncan-Knox** [comment] 2019-05-24 13:06
Happy to close this issue from my checks. Unless anyone has a reason to keep open.

**Closed as completed** 2019-05-24 13:18 UTC
Labels: Frontend, Query builder
