### ISSUE TITLE
Calculate

### ISSUE THREAD

**Issue by k8hughes** [devinit/ddw-analyst-ui#37] opened 2019-02-15 08:13 UTC
Select datasource, select columns, select transformation

The step by step element for the implementation of this probably should be sketched and share with the team so that we are all in agreement.  @akmiller01 had a clear idea of what the user needs here.

**Comment by Duncan-Knox** [comment] 2019-04-25 14:17
Similar to issue raised here: https://github.com/devinit/ddw-analyst-ui/issues/39.

Scalar transform and Multi transform do not allow the user to select any columns under the 'On' box.

**Comment by Duncan-Knox** [comment] 2019-05-01 15:35
Scalar transform options Add, Multiply, Power Subtract and Divide run smoothly. 

Option Concatanate appears to Concatanate with the title of the column selected under 'on' as opposed to the value on a single row. IE typing 'X' to concatanate with a column called 'ISO3' will mean each cell in newly formed 'ISO3 concat' will show as 'ISO3 X' as opposed to 'AFG X' .. 'BHU X' and so on. Flagging as this is quite possibly a bug?

Was also wondering if the concatanate function would have an aim to be developed to allow a merge between multiple columns as well as manually added text?

**Comment by akmiller01** [comment] 2019-05-01 15:40
That's the intended behavior for concatenate in it's scalar form. We would need to add a multi transform version of concat to concatenate multiple columns together.

**Comment by Duncan-Knox** [comment] 2019-05-01 15:48
Noted on the multiple columns concat being something that would not go on scalar and would be part of multi transform instead. Not a request as such for the time being.

Is scalar transform concat merging with the column title intended behaviour? I ask as the numerical scalars are applied to the row values within columns. Guess the same logic may have been in place for concat, hence the comment, unless I'm missing something?

**Comment by akmiller01** [comment] 2019-05-01 15:51
Ah okay, no I misread your message. Every row shows as "ISO3 X" for e.g.?

**Comment by Duncan-Knox** [comment] 2019-05-01 15:55
erm like this: 

![image](https://user-images.githubusercontent.com/13347058/57026467-cd980480-6c31-11e9-9c14-e7f1a95347a8.png)

Wondering if that was intentional and if so what the logic was?

**Comment by Duncan-Knox** [comment] 2019-05-01 15:56
As would have guessed it would show 'AFGX' and so on, instead of 'ISO3X' if that makes sense?

**Comment by akmiller01** [comment] 2019-05-01 15:58
Yep, that is a bug. Working on a fix.

**Comment by akmiller01** [comment] 2019-05-01 15:58
Will be here https://github.com/devinit/ddw-analyst-ui/pull/90

**Comment by Duncan-Knox** [comment] 2019-05-01 16:00
Ah right great, noted.

**Comment by akmiller01** [comment] 2019-05-01 16:25
Fixed in the PR 
![image](https://user-images.githubusercontent.com/2836840/57028108-3ec4c100-6c0c-11e9-9302-0152e86e1359.png)

**Comment by Duncan-Knox** [comment] 2019-05-01 16:26
Brilliant!

**Comment by edwinmp** [comment] 2019-05-10 07:56
@Duncan-Knox any further issues on this?

**Comment by Duncan-Knox** [comment] 2019-05-10 08:29
Hi @edwinmp. Not specifically. I'll set a note to self to check any additional features added to multi-transform.

**Comment by k8hughes** [comment] 2019-05-13 08:33
@Duncan-Knox can this be moved to "done"?

**Comment by Duncan-Knox** [comment] 2019-05-13 08:37
Yes, I believe so. Although. I'd aim to test additional features if/when they are added on.

**Closed as completed** 2019-05-13 10:27 UTC
Labels: Frontend, Query builder
