### ISSUE TITLE
Error saving query

### ISSUE THREAD

**Issue by bill-anderson** [devinit/ddw-analyst-ui#382] opened 2020-12-15 17:02 UTC
I think it saved but still get this error when pressing save.
![qb1](https://user-images.githubusercontent.com/3491562/102246928-327f9b80-3ef7-11eb-8890-12fc469f3195.png)

**Comment by bill-anderson** [comment] 2020-12-15 17:16
It didn't save. The example above was a copy of an existing query - it made the copy but won't save my edit.

I have now tried to create a new query and it won't save.

This makes this very urgent!!

**Comment by edwinmp** [comment] 2020-12-15 18:25
Hi @bill-anderson ... this should now be fixed. Still, I'm leaving it open as requiring auditing so we can know why it happened and make sure it doesn't happen again.

**Dev Note:** this was caused by a celery issue, seemingly originating from an incomplete deployment.

**Comment by edwinmp** [comment] 2021-02-17 18:40
The most common cause of this issue was fixed in the latest deployment.

**Closed as completed by edwinmp** 2021-02-17 18:40 UTC
Labels: bug, High Priority, Five Whys, pinned
